const propertyToSchemaMap = {
    companyName: { section: 'about', prompt: '' },
    tagline: { section: 'about', prompt: 'Create a tag line for Airbus SE company with the given description. Keep the output in under 50 characters.' },
    logo: { section: 'about'}, 
    primaryColor: { section: 'about'},
    secondaryColor: { section: 'about'},
    establishmentYear: { section: 'companyDetails', prompt: 'When was the company established?' },
    companyOverview: { section: 'companyDetails', prompt: 'Provide an overview of the company.' },
    problemDescription: { section: 'problemDescription', prompt: 'Describe the problem the company aims to solve.' },
    solutionsDescription: { section: 'solutionDescription', prompt: 'Convert the proposed solution into as few unique points as necessary, while ensuring they are mutually exclusive. Aim for minimum number of points while not exceeding 4 points.Only focus on the points which talk about the solutions and remove the points which talk about problems or opportunity. Merge the points associated with the same solution type in a single point. Keep the length of each point between 150 and 200 characters.' },
    sector: { section: 'market', prompt: 'What sector does the company operate in?' },
    otherSector: { section: 'market', prompt: 'Specify any other sectors the company operates in.' },
    marketDescription: { section: 'market', prompt: 'Describe the market the company targets.' },
    TAM: { section: 'market', prompt: 'What is the Total Addressable Market (TAM)?' },
    TAMGrowthRate: { section: 'market', prompt: 'What is the growth rate of the TAM?' },
    SAM: { section: 'market', prompt: 'What is the Serviceable Addressable Market (SAM)?' },
    SAMGrowthRate: { section: 'market', prompt: 'What is the growth rate of the SAM?' },
    productOverview: { section: 'product', prompt: 'Provide an overview of the product.' },
    productRoadmap: { section: 'product', prompt: 'Does the product have a roadmap?' },
    productRoadmapDescription: { section: 'product', prompt: 'Describe the product roadmap.' },
    technicalArchitecture: { section: 'product', prompt: 'Describe the technical architecture of the product.' },
    appType: { section: 'productScreen', prompt: 'What type of app is it?' },
    mobileScreenshots: { section: 'productScreen', prompt: 'Provide mobile screenshots of the product.' },
    webScreenshots: { section: 'productScreen', prompt: 'Provide web screenshots of the product.' },
    businessModel: { section: 'businessModel', prompt: 'Describe the business model.' },
    keyStakeholders: { section: 'goToMarket', prompt: 'Who are the key stakeholders?' },
    customerPersona: { section: 'goToMarket', prompt: 'Describe the customer persona.' },
    goToMarketStrategy: { section: 'goToMarket', prompt: 'What is the go-to-market strategy?' },
    trackRecord: { section: 'trackRecord', prompt: 'Provide the track record of the company.' },
    caseStudies: { section: 'caseStudies', prompt: 'Provide case studies related to the company.' },
    testimonials: { section: 'testimonials', prompt: 'Provide testimonials for the company.' },
    competitors: { section: 'competitors', prompt: 'Who are the competitors?' },
    competitiveDiff: { section: 'competitiveDiff', prompt: 'What is the competitive differentiation?' },
    teamMembers: { section: 'teamMembers', prompt: 'List the team members.' },
    websiteLink: { section: 'contactInfo', prompt: 'Provide the website link.' },
    linkedinLink: { section: 'contactInfo', prompt: 'Provide the LinkedIn link.' },
    contactEmail: { section: 'contactInfo', prompt: 'Provide the contact email.' },
    contactPhone: { section: 'contactInfo', prompt: 'Provide the contact phone number.' },
    financialSnapshot: { section: 'financialInfo', prompt: 'Provide the financial snapshot.' },
    revenueCost: { section: 'financialInfo', prompt: 'Provide the revenue and cost details.' },
    plannedRaise: { section: 'financialInfo', prompt: 'What is the planned raise?' },
    useOfFunds: { section: 'financialInfo', prompt: 'How will the funds be used?' },
    percentage: { section: 'financialInfo', prompt: 'What percentage of the company is being offered?' }
  };
  
  module.exports = propertyToSchemaMap;
  