const mongoose = require('mongoose');

const aboutResponseSchema = new mongoose.Schema({
  companyName: { type: String, default: '' },
  companyLogo: { type: String, default: '' },
  primaryColorR: { type: Number, default: 0 },
  primaryColorG: { type: Number, default: 0 },
  primaryColorB: { type: Number, default: 0 },
  primaryColorCheck: { type: String, default: '' },
  secondaryColorR: { type: Number, default: 0 },
  secondaryColorG: { type: Number, default: 0 },
  secondaryColorB: { type: Number, default: 0 },
  secondaryColorCheck: { type: String, default: '' },
  colorP100: { type: String, default: '' },
  colorP75_S25: { type: String, default: '' },
  colorP50_S50: { type: String, default: '' },
  colorP25_S75: { type: String, default: '' },
  colorS100: { type: String, default: '' },
  colorF_S100: { type: String, default: '' },
  colorF_P100: { type: String, default: '' },
  SCL: { type: String, default: '' },
  SCD: { type: String, default: '' },
  tagLine: { type: String, default: '' },
  coverImage: { type: String, default: 'this is cover image' },
  aboutTitle: { type: String, default: 'About Us' },
  aboutVision: { type: String, default: '' },
  aboutGPT: { type: String, default: '' },
  aboutGPTCleaned: { type: String, default: ''},
  aboutGPT1: { type: String, default: '' },
  aboutGPT2: { type: String, default: '' },
  aboutGPT3: { type: String, default: '' },
  aboutGPT4: { type: String, default: '' },
  aboutGPT5: { type: String, default: '' },
  aboutHeader1: { type: String, default: '' },
  aboutHeader2: { type: String, default: '' },
  aboutHeader3: { type: String, default: '' },
  aboutHeader4: { type: String, default: '' },
  aboutHeader5: { type: String, default: '' },
  about1: { type: String, default: '' },
  about2: { type: String, default: '' },
  about3: { type: String, default: '' },
  about4: { type: String, default: '' },
  about5: { type: String, default: '' },
  aboutImageURL: { type: String, default: '' }
});

module.exports = aboutResponseSchema;
