const mongoose = require('mongoose');

const competitorsResponseSchema = new mongoose.Schema({
  company1: { type: String, default: '' },
  company2: { type: String, default: '' },
  company3: { type: String, default: '' },
  company4: { type: String, default: '' },
  company5: { type: String, default: '' },
  company6: { type: String, default: '' },
  company7: { type: String, default: '' },
  attributeGPT: { type: String, default: '' },
  attributeGPTCleaned: { type: String, default: '' },
  attributeGPT1: { type: String, default: '' },
  attributeGPT2: { type: String, default: '' },
  attributeGPT3: { type: String, default: '' },
  attributeGPT4: { type: String, default: '' },
  attributeGPT5: { type: String, default: '' },
  attribute1: { type: String, default: '' },
  attribute2: { type: String, default: '' },
  attribute3: { type: String, default: '' },
  attribute4: { type: String, default: '' },
  attribute5: { type: String, default: '' },
  attribute1Ratings: { type: Array, default: [3,3,3,3,3] },
  attribute2Ratings: { type: Array, default: [3,3,3,3,3] },
  attribute3Ratings: { type: Array, default: [3,3,3,3,3] },
  attribute4Ratings: { type: Array, default: [3,3,3,3,3] },
  attribute5Ratings: { type: Array, default: [3,3,3,3,3] },
  company1Attribute1: { type: String, default: '' },
  company1Attribute2: { type: String, default: '' },
  company1Attribute3: { type: String, default: '' },
  company1Attribute4: { type: String, default: '' },
  company1Attribute5: { type: String, default: '' },
  company2Attribute1: { type: String, default: '' },
  company2Attribute2: { type: String, default: '' },
  company2Attribute3: { type: String, default: '' },
  company2Attribute4: { type: String, default: '' },
  company2Attribute5: { type: String, default: '' },
  company3Attribute1: { type: String, default: '' },
  company3Attribute2: { type: String, default: '' },
  company3Attribute3: { type: String, default: '' },
  company3Attribute4: { type: String, default: '' },
  company3Attribute5: { type: String, default: '' },
  company4Attribute1: { type: String, default: '' },
  company4Attribute2: { type: String, default: '' },
  company4Attribute3: { type: String, default: '' },
  company4Attribute4: { type: String, default: '' },
  company4Attribute5: { type: String, default: '' },
  company5Attribute1: { type: String, default: '' },
  company5Attribute2: { type: String, default: '' },
  company5Attribute3: { type: String, default: '' },
  company5Attribute4: { type: String, default: '' },
  company5Attribute5: { type: String, default: '' },
  company6Attribute1: { type: String, default: '' },
  company6Attribute2: { type: String, default: '' },
  company6Attribute3: { type: String, default: '' },
  company6Attribute4: { type: String, default: '' },
  company6Attribute5: { type: String, default: '' },
  company7Attribute1: { type: String, default: '' },
  company7Attribute2: { type: String, default: '' },
  company7Attribute3: { type: String, default: '' },
  company7Attribute4: { type: String, default: '' },
  company7Attribute5: { type: String, default: '' }
});

module.exports = competitorsResponseSchema;
