const mongoose = require('mongoose');

const gtmResponseSchema = new mongoose.Schema({
  stakeholdersTitle: { type: String, default: '' },
  stakeholderGPT: { type: String, default: '' },
  stakeholderGPTCleaned: { type: String, default: '' },
  stakeholderGPT1: { type: String, default: '' },
  stakeholderGPT2: { type: String, default: '' },
  stakeholderGPT3: { type: String, default: '' },
  stakeholderGPT4: { type: String, default: '' },
  stakeholder1: { type: String, default: '' },
  stakeholder2: { type: String, default: '' },
  stakeholder3: { type: String, default: '' },
  stakeholder4: { type: String, default: '' },
  benefits1: { type: String, default: '' },
  benefits2: { type: String, default: '' },
  benefits3: { type: String, default: '' },
  benefits4: { type: String, default: '' },
  customerProfileIcon1: { type: String, default: '' },
  customerProfileIcon2: { type: String, default: '' },
  customerProfileIcon3: { type: String, default: '' },
  customerProfileIcon4: { type: String, default: '' },
  customerProfileCoverImage: { type: String, default: '' },
  persona: { type: String, default: '' },
  personaCategoryGPT: { type: String, default: '' },
  personaCategoryGPTCleaned: { type: String, default: '' },
  personaCategoryGPT1: { type: String, default: '' },
  personaCategoryGPT2: { type: String, default: '' },
  personaCategoryGPT3: { type: String, default: '' },
  personaHeader1: { type: String, default: '' },
  personaHeader2: { type: String, default: '' },
  personaHeader3: { type: String, default: '' },
  personaDescription1: { type: String, default: '' },
  personaDescription2: { type: String, default: '' },
  personaDescription3: { type: String, default: '' },
  personaIcon1: { type: String, default: '' },
  personaIcon2: { type: String, default: '' },
  personaIcon3: { type: String, default: '' },
  gtmTitle: { type: String, default: '' },
  gtmOverview: { type: String, default: '' },
  gtmCoverImageLandscape: { type: String, default: '' },
  gtmGPT: { type: String, default: '' },
  gtmGPTCleaned: { type: String, default: '' },
  gtmGPT1: { type: String, default: '' },
  gtmGPT2: { type: String, default: '' },
  gtmGPT3: { type: String, default: '' },
  gtmGPT4: { type: String, default: '' },
  gtmGPT5: { type: String, default: '' },
  gtmHeader1: { type: String, default: '' },
  gtmHeader2: { type: String, default: '' },
  gtmHeader3: { type: String, default: '' },
  gtmHeader4: { type: String, default: '' },
  gtmHeader5: { type: String, default: '' },
  gtmDescription1: { type: String, default: '' },
  gtmDescription2: { type: String, default: '' },
  gtmDescription3: { type: String, default: '' },
  gtmDescription4: { type: String, default: '' },
  gtmDescription5: { type: String, default: '' },
  gtmIcon1: { type: String, default: '' },
  gtmIcon2: { type: String, default: '' },
  gtmIcon3: { type: String, default: '' },
  gtmIcon4: { type: String, default: '' },
  gtmIcon5: { type: String, default: '' }
});

module.exports = gtmResponseSchema;
