const mongoose = require('mongoose');

const productResponseSchema = new mongoose.Schema({
  productTitle: { type: String, default: '' },
  productOverview: { type: String, default: '' },
  featureGPT: { type: String, default: '' },
  featureGPTCleaned: { type: String, default: '' },
  featureGPT1: { type: String, default: '' },
  featureGPT2: { type: String, default: '' },
  featureGPT3: { type: String, default: '' },
  featureGPT4: { type: String, default: '' },
  featureGPT5: { type: String, default: '' },
  featureGPT6: { type: String, default: '' },
  feature1: { type: String, default: '' },
  feature2: { type: String, default: '' },
  feature3: { type: String, default: '' },
  feature4: { type: String, default: '' },
  feature5: { type: String, default: '' },
  feature6: { type: String, default: '' },
  featureDescription1: { type: String, default: '' },
  featureDescription2: { type: String, default: '' },
  featureDescription3: { type: String, default: '' },
  featureDescription4: { type: String, default: '' },
  featureDescription5: { type: String, default: '' },
  featureDescription6: { type: String, default: '' },
  featureIcon1: { type: String, default: '' },
  featureIcon2: { type: String, default: '' },
  featureIcon3: { type: String, default: '' },
  featureIcon4: { type: String, default: '' },
  featureIcon5: { type: String, default: '' },
  featureIcon6: { type: String, default: '' },
  productRoadmapTitle: { type: String, default: '' },
  phaseGPT: { type: String, default: '' },
  phaseGPTCleaned: { type: String, default: '' },
  phaseGPT1: { type: String, default: '' },
  phaseGPT2: { type: String, default: '' },
  phaseGPT3: { type: String, default: '' },
  phaseHeader1Name: { type: String, default: '' },
  phaseHeader2Name: { type: String, default: '' },
  phaseHeader3Name: { type: String, default: '' },
  phaseDescription1: { type: String, default: '' },
  phaseDescription2: { type: String, default: '' },
  phaseDescription3: { type: String, default: '' },
  phaseFeatures1: { type: String, default: '' },
  phaseFeatures2: { type: String, default: '' },
  phaseFeatures3: { type: String, default: '' },
  inputs: { type: String, default: '' },
  technologyPlatform: { type: String, default: '' },
  valueBasedOutput: { type: String, default: '' }
});

module.exports = productResponseSchema;
